In [65]:
import pandas as pd
import numpy as np

import nltk
from nltk.tokenize import word_tokenize

In [66]:
data = "La cada, ¿De quien estras? cat par-perro"

# tokenization of sentence into words
tokens = word_tokenize(data)
tokens


['La', 'cada', ',', '¿De', 'quien', 'estras', '?', 'cat', 'par-perro']

In [67]:
len(tokens)

9

Obtemeos `stop-words` nltk

In [68]:
from nltk.corpus import stopwords

stropwords = list(stopwords.words('spanish'))

In [69]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(lowercase=True, stop_words=stropwords, max_features=5)

corpus = ['Keras: Aunque es más conocida como una biblioteca de aprendizaje profundo, Keras', 'tambien proporciona utilidades para la tokenización de texto.']




In [70]:
X = count_vectorizer.fit_transform(corpus)

In [72]:
count_vectorizer.vocabulary_

{'keras': 4, 'aunque': 1, 'conocida': 3, 'biblioteca': 2, 'aprendizaje': 0}

## Bag of words (BD)

In [87]:
from sklearn.feature_extraction.text import CountVectorizer

# Definimos nuestro corpus de documentos
corpus = [
    'La casa de macri es turra',
    'macri es gato',
    'los peces se van a noruega',
    '¿Es este el primer documento?',
]

# Creamos el vectorizador de conteo
vectorizer = CountVectorizer()

# Ajustamos y transformamos nuestro corpus
X = vectorizer.fit_transform(corpus)

# Obtenemos las características (palabras únicas en el corpus), retorna un nrray
features = vectorizer.get_feature_names_out()

# Imprimimos las características y la matriz de términos-documento
print("Características: ", features)
print("Matriz de términos-documento: \n", X.toarray())


Características:  ['casa' 'de' 'documento' 'el' 'es' 'este' 'gato' 'la' 'los' 'macri'
 'noruega' 'peces' 'primer' 'se' 'turra' 'van']
Matriz de términos-documento: 
 [[1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 1]
 [0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0]]


In [88]:
# Obtenemos las características (palabras únicas en el corpus), retorna un dict
vectorizer.vocabulary_

{'la': 7,
 'casa': 0,
 'de': 1,
 'macri': 9,
 'es': 4,
 'turra': 14,
 'gato': 6,
 'los': 8,
 'peces': 11,
 'se': 13,
 'van': 15,
 'noruega': 10,
 'este': 5,
 'el': 3,
 'primer': 12,
 'documento': 2}

In [89]:
vectorizer.transform(["todos los gatos son noruegos"]).todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)