In [23]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

# Crear un DataFrame de ejemplo con valores faltantes
data = pd.DataFrame({
    'A': [25,27,29,31,33, np.nan],
    'B': [np.nan, 3,5,7,9,11],
    'C': [50, np.nan, 80,90,100,130],
})

data


A     B      C
0  25.0   NaN   50.0
1  27.0   3.0    NaN
2  29.0   5.0   80.0
3  31.0   7.0   90.0
4  33.0   9.0  100.0
5   NaN  11.0  130.0

In [36]:
# Configurar el IterativeImputer con regresión lineal (BayesianRidge)
from sklearn.linear_model import BayesianRidge


imputer = IterativeImputer(estimator=LinearRegression(), initial_strategy='mean',  max_iter=1, random_state=0)

# Aplicar la imputación
imputed_data = imputer.fit_transform(data)

# Convertir el resultado a un DataFrame
imputed_df = pd.DataFrame(imputed_data, columns=data.columns)

print(imputed_df)


       A         B           C
0  25.00   4.05042   50.000000
1  27.00   3.00000   68.532626
2  29.00   5.00000   80.000000
3  31.00   7.00000   90.000000
4  33.00   9.00000  100.000000
5  38.75  11.00000  130.000000


c:\Users\lufer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\impute\_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


# Paso a paso

In [76]:
from sklearn.impute import SimpleImputer


SimpleImputer = SimpleImputer(strategy='mean')
SimpleImputer.fit(data)
data_imputed = SimpleImputer.transform(data)
data_imputed

array([[ 25.,   7.,  50.],
       [ 27.,   3.,  90.],
       [ 29.,   5.,  80.],
       [ 31.,   7.,  90.],
       [ 33.,   9., 100.],
       [ 29.,  11., 130.]])

Columna A fila 5, tienen NAN

In [82]:
df = pd.DataFrame({
    'A': [25, 27, 29,31,33],
    'B': [7,3, 5, 7, 9],
    'C': [50, 90, 80,90,100],
})

In [83]:
# entremaos un meodle de regrson lineal
model = LinearRegression()
model.fit(df[['B','C']], df['A'])
model.predict([[11, 130]])

c:\Users\lufer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.75])

In [84]:
df = pd.DataFrame({
    'A': [27,29,31,33, 38.75],
    'B': [3,5,7,9, 11],
    'C': [90, 80,90,100, 130],
})
model = LinearRegression()
model.fit(df[['A','C']], df['B'])
model.predict([[25, 50]])

c:\Users\lufer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.05042017])

In [86]:
df = pd.DataFrame({
    'A': [25, 29, 31, 33, 38.75],
    'B': [4.05042017, 5, 7, 9, 11],
    'C': [50, 80, 90,100, 130],
})
model = LinearRegression()
model.fit(df[['A','B']], df['C'])
model.predict([[27, 3]])

c:\Users\lufer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68.5326265])